### ISSUE TITLE
How to detect 360-degree spin?

### ISSUE THREAD

**Issue by mfialaf** [Roger-random/ESP32Tests#1]
Hi Roger,
This is not an issue, but more question.
I really like your example in StepperVelocity with the spinning motor. Finally nice, well commented, example where I can easily adjust the speed. I am playing a little with a stepper motor, TMC2209 and esp32 in ESP-IDF.

My question is, is there a way to easily detect f.x 360-degree spin and then stop?

I've tried to put a counter in the while(1) loop, but with changing the speed, also the number when it reaches 360-degree, changes.
If you have some free time can you please help me?

P.S I also noticed that you mention "Position control is not an objective here, thus the number of steps are not counted." So maybe you have a better example for adjusting the speed and also the position control. I am not using a potentiometer so neither ADC.

Thanks in advance, Marek.

**Comment by Roger-random** [comment]
Confirm that my exercise objective does not match your project. It may be more useful to look at an ESP32 project focused on positional control, for example the ESP32 port of grblHAL CNC software.
https://github.com/grblHAL/ESP32

- -

I haven't tried to do what you described, so I have no firsthand knowledge to share. Just some guesses.

Maybe the PCNT (pulse counter) peripheral of an ESP32 can help?
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/pcnt.html
It should be able to count the number of steps that correspond to a target position. I don't know if the ESP32 GPIO matrix can internally wire PCNT to LEDC PWM signal, if not the connection will have to be made externally.

Alternatively: Look at the TMC2209 datasheet, the INDEX pin (#12) might be better for PCNT than the actual step pulses since it aligns with coil phase.

- -

I will close this item because as you said it is not an issue with the code in my repository.
